"""Project-wide constants and portable filesystem paths."""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

START_DATE = "2025-07-01"
END_DATE = "2025-12-31"

TARGET_SAMPLE_SIZE = 3_000
RANDOM_SEED = 20_250_911

COUNTRY_CODE = "us"
LANGUAGE = "english"
CURRENCY = "USD"

MIN_REVIEWS_FOR_MODEL = 20

REVIEW_LANGUAGE = "all"
REVIEW_PURCHASE_TYPE = "steam"
REVIEW_TYPE = "all"
REVIEW_FILTER = "all"
REVIEW_CURSOR = "*"
FILTER_OFFTOPIC_ACTIVITY = 1
REVIEW_NUM_PER_PAGE = 1
REVIEW_DAY_RANGE = 365
REVIEW_PREFLIGHT_FILTER = "summary"
REVIEW_PREFLIGHT_NUM_PER_PAGE = 0
REVIEW_PREFLIGHT_SIZE = 30
REVIEW_QUERY_CONTRACT_TEST_SIZE = 10

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
SEARCH_RAW_DATA_DIR = RAW_DATA_DIR / "search"
CATALOG_RAW_DATA_DIR = RAW_DATA_DIR / "catalog"
APPDETAILS_RAW_DATA_DIR = RAW_DATA_DIR / "appdetails"
APPDETAILS_PREFLIGHT_RAW_DATA_DIR = APPDETAILS_RAW_DATA_DIR / "preflight"
REVIEW_RAW_DATA_DIR = RAW_DATA_DIR / "reviews"
REVIEW_PREFLIGHT_RAW_DATA_DIR = REVIEW_RAW_DATA_DIR / "preflight"
REVIEW_QUERY_CONTRACT_RAW_DATA_DIR = REVIEW_RAW_DATA_DIR / "query_contract_test"
REVIEW_FULL_RAW_DATA_DIR = REVIEW_RAW_DATA_DIR / "full"
LOG_DIR = PROJECT_ROOT / "logs"
REPORT_DIR = PROJECT_ROOT / "reports"

CANDIDATE_DISCOVERED_PATH = INTERIM_DATA_DIR / "candidate_games_discovered.csv"
CANDIDATE_CANONICAL_PATH = INTERIM_DATA_DIR / "candidate_games_canonical.csv"
SEARCH_CHECKPOINT_PATH = INTERIM_DATA_DIR / "search_checkpoint.json"
OFFICIAL_CATALOG_PATH = INTERIM_DATA_DIR / "official_game_catalog.csv"
CATALOG_CHECKPOINT_PATH = INTERIM_DATA_DIR / "catalog_checkpoint.json"
CANDIDATE_CATALOG_MATCH_PATH = INTERIM_DATA_DIR / "candidate_catalog_match.csv"
APPDETAILS_METADATA_PATH = INTERIM_DATA_DIR / "candidate_appdetails.csv"
APPDETAILS_PREFLIGHT_SAMPLE_PATH = (
    INTERIM_DATA_DIR / "appdetails_preflight_sample.csv"
)
APPDETAILS_PREFLIGHT_METADATA_PATH = (
    INTERIM_DATA_DIR / "appdetails_preflight_metadata.csv"
)
APPDETAILS_PREFLIGHT_AUDIT_PATH = (
    INTERIM_DATA_DIR / "appdetails_preflight_eligibility_audit.csv"
)
APPDETAILS_PREFLIGHT_ELIGIBLE_PATH = (
    INTERIM_DATA_DIR / "appdetails_preflight_eligible.csv"
)
APPDETAILS_PREFLIGHT_GENRES_PATH = (
    INTERIM_DATA_DIR / "appdetails_preflight_game_genres.csv"
)
ELIGIBILITY_AUDIT_PATH = INTERIM_DATA_DIR / "eligibility_audit.csv"
ELIGIBLE_SAMPLING_FRAME_PATH = INTERIM_DATA_DIR / "eligible_sampling_frame.csv"
SAMPLE_GAMES_PATH = PROCESSED_DATA_DIR / "sample_games.csv"
GAMES_PATH = PROCESSED_DATA_DIR / "games.csv"
GAME_GENRES_PATH = PROCESSED_DATA_DIR / "game_genres.csv"
STEP2_REPORT_PATH = REPORT_DIR / "step2_candidate_report.md"
APPDETAILS_PREFLIGHT_REPORT_PATH = (
    REPORT_DIR / "step2c_appdetails_preflight_report.md"
)
STEP3A_METADATA_REPORT_PATH = REPORT_DIR / "step3a_metadata_report.md"
REVIEW_PREFLIGHT_SAMPLE_PATH = INTERIM_DATA_DIR / "review_preflight_sample.csv"
REVIEW_PREFLIGHT_SNAPSHOT_PATH = INTERIM_DATA_DIR / "review_preflight_snapshot.csv"
REVIEW_QUERY_CONTRACT_SAMPLE_PATH = (
    INTERIM_DATA_DIR / "review_query_contract_sample.csv"
)
REVIEW_QUERY_CONTRACT_COMPARISON_PATH = (
    INTERIM_DATA_DIR / "review_query_contract_comparison.csv"
)
REVIEW_COLLECTION_AUDIT_PATH = (
    INTERIM_DATA_DIR / "review_snapshot_collection_audit.csv"
)
REVIEW_SNAPSHOTS_PATH = PROCESSED_DATA_DIR / "review_snapshots.csv"
STEP3B_PREFLIGHT_REPORT_PATH = REPORT_DIR / "step3b_review_preflight_report.md"
STEP3B_QUERY_CONTRACT_REPORT_PATH = (
    REPORT_DIR / "step3b_query_contract_report.md"
)
STEP3B_FULL_REVIEW_REPORT_PATH = REPORT_DIR / "step3b_full_review_report.md"
STEP3B_FINAL_AUDIT_REPORT_PATH = REPORT_DIR / "step3b_final_audit.md"

FROZEN_INPUT_SHA256 = {
    SAMPLE_GAMES_PATH: "320A52FC8F4B8D5B71C2AA113B8B675D6B721C209A6EDB9C055658535395CB4F",
    GAMES_PATH: "11D102600A178A9772BFD763CA2BF64A32534C338709E8E86CE013B4A17BBCE0",
    GAME_GENRES_PATH: "A718A498F0244D5FBD2A3862CDF49B0987C8DD5708F1A8C0826C14FDF6E17659",
    ELIGIBLE_SAMPLING_FRAME_PATH: "B989B8CB249FF52851996E416481FDA8AEAF3C853D2A580757BD63DAF704BF1B",
}
REVIEW_SNAPSHOT_SHA256 = (
    "D219D3DBBD9CE1502122E78D1B8E7CC8958A5EE645311D3B30E382F75CF5D3BB"
)

STEAM_SEARCH_URL = "https://store.steampowered.com/search/results/"
STEAM_APPDETAILS_URL = "https://store.steampowered.com/api/appdetails"
STEAM_REVIEWS_URL = "https://store.steampowered.com/appreviews/{appid}"
STEAM_CATALOG_URL = (
    "https://api.steampowered.com/IStoreService/GetAppList/v1/"
)

SEARCH_PAGE_SIZE = 50
STOP_AFTER_OLD_PAGES = 3
CATALOG_PAGE_SIZE = 10_000
REQUEST_TIMEOUT_SECONDS = 30
REQUEST_DELAY_SECONDS = 2.0
REQUEST_JITTER_SECONDS = 0.25
MAX_RETRIES = 5
BACKOFF_BASE_SECONDS = 1.0
USER_AGENT = "steam-game-analysis/1.0 (portfolio research project)"
